POST http://localhost:3029/addDestination
Content-Type: application/json

{
   "travel_location": "Vienna",
    "price":239.00,
    "cover_image": "https://tse1.mm.bing.net/th?id=OIP.rUclbL1c9hdkdAEbiLWrSgHaE8&pid=Api&P=0&h=180",
    "images_location":["https://tse1.mm.bing.net/th?id=OIP.W-PLjvV6w8Pi4Nmg1RSfUgHaE6&pid=Api&P=0&h=180",
    "https://tse1.mm.bing.net/th?id=OIP.9xbuhrruBORXoytCZlBo4gHaEo&pid=Api&P=0&h=180",
    "https://tse1.mm.bing.net/th?id=OIP.AB29-LX3gI4bHSJSa2ORrAHaE5&pid=Api&P=0&h=180",
    "https://tse3.mm.bing.net/th?id=OIP.T18Cddz7L6ZWVTSWxmvkQwHaE8&pid=Api&P=0&h=180",
    "https://tse2.mm.bing.net/th?id=OIP.7hbgwzGHGgQBRIHa0nRuagHaEo&pid=Api&P=0&h=180"] ,
    "description": "Città imperiale, patria della Secessione e della psicanalisi, Vienna offre ai suoi visitatori complessi museali, palazzi storici, giardini fioriti e un ricco calendario d’eventi. Con il Prater, i molti caffè, i locali di tendenza, l’isola del Danubio, la capitale fa godere momenti di cultura, svago, relax.",
    "main_attractions": "Il duomo di Santo Stefano. Iniziato nel XII secolo, con interni rimaneggiati nei secoli fino al barocco, oggi è il simbolo di Vienna e il più importante monumento gotico dell’Austria. Dai 136,44 metri della torre più alta, a cui si sale con 343 gradini, si gode una vista sconfinata su tutta Vienna.La Hofburg, uno dei più grandi palazzi imperiali esistenti al mondo, per secoli residenza degli Ausburgo. Oggi potete visitare sontuosi edifici, con giardini, musei, gli appartamenti degli Asburgo, la Scuola di equitazione spagnola.",
    "season" : "all_seasons"



}

####

GET http://localhost:3029/getWinterDestination/6616a937e8c1fe38d3dac4f0

####

POST http://localhost:3029/addUser
Content-Type: application/json

{
   "name": "Maoc",
   "email": "questaemaildiprova@email.it",
   "password": "prova",
   "role": "admin",
   "birthday": "04/12/1994",
   "avatar": "M"
}

####

POST http://localhost:3029/addReview/661a40d2feb1f986d6c0b9e9/reviews/661ceda3b8176522d2ed5d13
Content-Type: application/json

{
    "comment": "prova recensione",
    "evaluation_score": 3
}

####

GET http://localhost:3029/getUser/661556e743ece0502b142377

####

POST http://localhost:3029/login
Content-Type: application/json

{
    "email": "provaEmail@prova.it",
    "password": "prova"
}

####

POST http://localhost:3029/addImage
Content-Type: application/json

{
    "image": ["https://tse1.mm.bing.net/th?id=OIP._mkLI8xiiJuWH_mVc1SNIwHaEI&pid=Api&P=0&h=180",
    "https://res.cloudinary.com/boscolo-viaggi/image/upload/f_auto/t_PD-ContentImage-XXL/v1/Brand/BOSCOLO_MAROCCO_3155_ST_kprnot",
    "https://sp.yimg.com/ib/th?&id=ODL.024697a7a45720d277a07d88b45cc5b8&w=200&h=107&c=4&dpr=2&rs=1",
    "https://tse4.mm.bing.net/th?id=OIP.tPnc98gZYkK7G9VWgMTTuwHaDt&pid=Api&P=0&h=180",
    "https://tse2.mm.bing.net/th?id=OIP.Cf7252Qn1jfjpRVHGpOY3AHaD8&pid=Api&P=0&h=180",
    "https://tse4.mm.bing.net/th?id=OIP.BF4EbD35TEE4Gf8wNNugYAHaEX&pid=Api&P=0&h=180",
    "https://tse4.mm.bing.net/th?id=OIP.8sQx3RTajXbvH8bk5wsfGQHaEg&pid=Api&P=0&h=180",
    "https://tse4.mm.bing.net/th?id=OIP.X7DtnocJS9_c29Vz3CgXtAHaFF&pid=Api&P=0&h=180",
    "https://tse1.mm.bing.net/th?id=OIP.nFrilhT9VQNE1NQQeAhFWQHaEK&pid=Api&P=0&h=180",
    "https://tse1.mm.bing.net/th?id=OIP.Xi97O4pIIzl7GD-h3gHDxAHaE8&pid=Api&P=0&h=180",
    "https://tse1.mm.bing.net/th?id=OIP.lHaQxUleBXVg4oUlfT7rLQHaEK&pid=Api&P=0&h=180",
    "https://tse3.mm.bing.net/th?id=OIP.wGf-ll1QxtZcvwPe6gB7rwHaEK&pid=Api&P=0&h=180",
    "https://tse4.mm.bing.net/th?id=OIP.apOEsQDatiIbnvYyfFDnDQHaE8&pid=Api&P=0&h=180"
    ]
}

####

GET http://localhost:3029/getReviews