POST http://localhost:3029/addWinterDestination
Content-Type: application/json

{
   "travel_location": "Milano",
    "price":333,
    "image_location":"fds" ,
    "description": "ffggg",
    "main_attractions": "hhhgfgf"
}