POST http://localhost:3029/addAllSeasonsDestination
Content-Type: application/json

{
   "travel_location": "Budapest",
    "price":215.00,
    "cover_image": "https://www.10cose.it/wp-content/uploads/2017/02/capitale-budapest.jpg",
    "images_location":["https://www.10cose.it/wp-content/uploads/2015/10/castello-Buda-budapest.jpg",
    "https://www.10cose.it/wp-content/uploads/2018/05/chiesa-mattia-budapest-375x250-1.jpg",
    "https://www.10cose.it/wp-content/uploads/2015/10/pest-budapest.jpg",
    "https://www.10cose.it/wp-content/uploads/2015/10/grande-sinagoga-budapest.jpg",
    "https://www.10cose.it/wp-content/uploads/2015/10/isola-margherita-budapest.jpg",
    "https://www.10cose.it/wp-content/uploads/2015/10/parlamento-budapest.jpg"
                       ] ,
    "description": "Budapest, non a caso, è definita la “Parigi dell’Est“. La città ha molti tratti in comune con la capitale francese e alcuni scorci riportano subito alle vedute di Parigi: c’è un fiume, che taglia la città e su cui si affacciano castelli e bei palazzi, e c’è una collina simile a Montmartre su cui arrampicarsi per godersi il panorama su tutta Budapest.",
    "main_attractions": "Nel cuore di Buda si innalzano al cielo le guglie gotiche della Chiesa di Mattia. Costruita per volere del re Bèla IV nel XIII secolo, la Chiesa di Nostra Signora, dedicata alla Vergine, assunse successivamente l’attuale nome in onore del re ungherese Mattia Corvino, sovrano illuminato, che la fece ricostruire verso la fine del 1400 e che qui celebrò i suoi due matrimoni (da notare lo stemma reale, il corvo, sulla facciata della torre)."



}

####

GET http://localhost:3029/getWinterDestination/6616a937e8c1fe38d3dac4f0

####

POST http://localhost:3029/addReview/6616a6d08d8800259d3b8921
Content-Type: application/json

{
    "comment": "recensione",
    "evaluation_score":5
}

####

POST http://localhost:3029/addReview/6616a937e8c1fe38d3dac4f0/reviews/661556e743ece0502b142377
Content-Type: application/json

{
    "comment": "prova recensione",
    "evaluation_score": 3
}

####

GET http://localhost:3029/getUser/661556e743ece0502b142377